[package]
name = "ferris-say"
version = "0.1.0"
edition = "2021"
authors=["CinematicCow"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = { version = "3.1.8", features = ["derive"] }
